ignored = ["github.com/gopherjs/gopherjs", "github.com/gopherjs/gopherjs/js"]

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/goph/fxt"
  version = "0.5.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/hashicorp/go-memdb"
  branch = "master"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  branch = "master"

[[constraint]]
  name = "github.com/goph/clock"
  version = "0.1.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"


# Test dependencies
[[constraint]]
  name = "github.com/DATA-DOG/go-txdb"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.2"

# Web dependencies
[[constraint]]
  name = "github.com/oskca/gopherjs-vue"
  branch = "master"

# Transitive dependencies
[[constraint]]
  name = "github.com/go-kit/kit"

[[constraint]]
  name = "github.com/goph/emperror"

[[constraint]]
  name = "github.com/goph/healthz"

[[constraint]]
  name = "github.com/goph/stdlib"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "go.uber.org/dig"

[[constraint]]
  name = "go.uber.org/fx"

[[constraint]]
  name = "google.golang.org/grpc"
